name: stylerdalle
channels:
  - defaults
dependencies:
- python>=3.8
- pip>=21
- pip:
   - transformers~=4.10.2
   - ftfy
   - regex
   - tqdm
   - DALL-E
   - rudalle==1.1.3
   - git+https://github.com/openai/CLIP.git